name: 'Python Environment for Zephyr Actions'
description: 'Setup a Python environment to run Zephyr-related actions'
inputs:
  python-version:
    description: 'Version of Python to set up'
    required: false
    default: '3.12'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: ${{ github.action_path }}/requirements-actions.txt

    - name: Install Python packages
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          pip install -r "${{ github.action_path }}\requirements-actions.txt" --require-hashes
        else
          pip install -r ${{ github.action_path }}/requirements-actions.txt --require-hashes
        fi
